export const QUERY_KEYS = {
  purchase: 'purchase',
  orders: 'orders',
  ordersByStatus: 'ordersByStatus',
  ordersByUserId: 'ordersByUserId',
  favorites: 'favorites',
  address: 'address',
  broadcasts: 'broadcasts',
  category: 'category',
  product: 'product',
  province: 'province',
  cities: 'cities',
  ticket: 'ticket',
  department: 'department',
  question: 'question',
  content: 'content',
  search: 'search',
  cart: 'cart',
  deleteCartItem: 'deleteCartItem',
  addToCartTransaction: 'addToCartTransaction',
  shipping: 'shipping',
  packaging: 'packaging',
  order: 'order',
  createOrder: 'createOrder',
  payment: 'payment',
  vendor: 'vendor',
  test: 'test',
  comments: 'comments',
  deleteAddress: 'deleteAddress',
  faq: 'faq',
  terms: 'terms',
  about: 'about',
  user: 'user',
  credit: 'credit',
  shippingDelivery: 'shippingDelivery',
  slider: 'slider',
  banner: 'banner',
  remindOrder: 'remindOrder',
  brand:'brand',
};
export const STORE_KEYS = {};
